services:
  mysql:
    image: mysql:8.4.0
    container_name: mysqldb
    command: 
      - --mysql-native-password=ON
      - --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: ${BDD_ROOT_PASSWORD}
      MYSQL_DATABASE: ${BDD_NAME}
      MYSQL_USER: ${BDD_USER}
      MYSQL_PASSWORD: ${BDD_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev
    ports:
      - "1080:1080"   # Web UI
      - "1025:1025"   # SMTP server

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - minio-data:/data/minio

volumes:
  mysqldbdata:
  mongodbdata:
  minio-data:
    driver: local
